automation:
  - alias: Turn on LED strip with motion sensor
    trigger:
      - platform: state
        entity_id: binary_sensor.master_bed
        to: 'on'
    condition:
      - condition: time
        after: '00:00:00'
        before: '06:00:00'
      - condition: state
        entity_id: input_boolean.motion_sensor_disabled
        state: 'off'
    action:
      - service: light.turn_on
        entity_id: light.strip_led
        data:
          transition: 60
      - delay: '00:01:00'
      - service: light.turn_off
        entity_id: light.strip_led

  - alias: Turn on coffee machine with motion sensor in the morning
    trigger:
      - platform: state
        entity_id: binary_sensor.master_bed
        to: 'on'
        for:
          hours: 1
      - platform: time
        at: '06:00:00'
    condition:
      - condition: time
        after: '06:00:00'
        before: '07:00:00'
    action:
      - service: switch.turn_on
        entity_id: switch.coffeemachine
