
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt:
    binary_sensor:
      - unique_id: binary_sensor.garage_pir
        name: "garage_pir Sensor"
        state_topic: "sensor/Garage_Temp_PIR/PIR1"
        qos: 1
        payload_on: "ON"
        payload_not_available: "OFF"
        device_class: motion

sensor:
  - platform: time_date
    display_options:
      - 'date_time'

  - platform: worldclock
    time_zone: America/Sao_Paulo

